name: John & Rebecca Pratt
title: John & Rebecca Pratt

# remote_theme: ronv/ultra

baseurl: /pratt
#baseurl: https://raw.githubusercontent.com/Rkayak/pratt

exclude:
  - Gemfile
  - Gemfile.lock

# for dinky theme
# theme: jekyll-theme-dinky
# show_downloads: false
