name: Process Images

on: [pull_request]

jobs:

  imagemagick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: sudo apt install imagemagick
        continue-on-error: true

      - run: identify -format '%w %h %i\n' img/2011/*.JPG | awk '$1>1200||$2>1200' | cut -d\  -f3- | xargs -d\\n mogrify -resize 1200x1200\>
        shell: bash

      # - uses: jruipinto/ImageMagick-action@v1
      #   name: resize jpg
      #   with:
      #     # default ImageMagick command is:
      #     #   mogrify -path src/assets/images -auto-orient -resize x500 src/assets/images*.*
      #     command: identify -format '%w %h %i\n' img/*/*.jpg | awk '$1>1200||$2>1200' | cut -d\  -f3- | xargs -d\\n mogrify -resize 1200x1200\>
      #   continue-on-error: true
      #   shell: bash

      # - uses: jruipinto/ImageMagick-action@v1
      #   name: resize JPG
      #   with:
      #     command: identify -format '%w %h %i\n' img/*/*.JPG | awk '$1>1200||$2>1200' | cut -d\  -f3- | xargs -d\\n mogrify -resize 1200x1200\>
      #   continue-on-error: true

      # - uses: jruipinto/ImageMagick-action@v1
      #   name: resize png
      #   with:
      #     command: identify -format '%w %h %i\n' img/*/*.png|awk '$1>1200||$2>1200'|cut -d\  -f3-|xargs -d\\n mogrify -resize 1200x1200>
      #   continue-on-error: true

      - name: git commit
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/Rkayak/pratt
          git config user.name github-actions
          git config user.email github-actions@github.com
          find . -name '*~' -delete
          git add img
          git commit -m "update images"
          git push


# https://github.com/marketplace/actions/resize-images
#   pillow:
#     name: Github Action Image Resizing
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Resize Images
#         id: resize-images
#         uses: gonzalonaveira/gh-image-resizing@master
#         with:
#           IMAGES_MAX_WIDTH: "1600"
#           IMAGES_QUALITY: "90"
#           IMAGES_FORMATS: "jpg, jpge, png"
#           IMAGES_DIRECTORIES: "img"
#       - name: Commit changes
#         uses: EndBug/add-and-commit@v4
#         with:
#           add: 'img/'
#           author_name: "github-actions[bot]"
#           author_email: "github-actions@users.noreply.github.com"
#           message: |
#             Images Resized by Github action
#             ${{steps.resize-images.outputs.result}}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


